services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cashtrackr
    container_name: cashtrackr
    volumes:
      - ./postgres:/var/lib/postgresql/data